{% set version = "0.2.2" %}

package:
  name: jsonschema-spec
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jsonschema-spec/jsonschema_spec-{{ version }}.tar.gz
  sha256: a5c98c2b0be73a1b3cf8464b8a300210d1006eb086ffb9fb0e58b19052ec86ec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - poetry-core >=1.0.0
    - python >=3.8
    - pip
  run:
    # sync from poetry-generated setup.py rather than pyproject.toml; use typing_extensions
    - pathable >=0.4.1,<0.5.0
    - python >=3.8
    - pyyaml >=5.1
    - referencing >=0.28.4,<0.30.0
    - requests >=2.31.0,<3
    - typing_extensions >=4.3.0,<5.0.0

test:
  imports:
    - jsonschema_spec
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/p1c2u/jsonschema-spec
  summary: JSONSchema Spec with object-oriented paths
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
